branch-defaults:
  default:
    environment: null
global:
  application_name: TodoClient
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: 5.8.2
  profile: null
  repository: null
  sc: null
  workspace_type: Application
