name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # backend:
  #   runs-on: ubuntu-latest
  #   env:
  #   # https://www.serverless.com/framework/docs/guides/cicd/running-in-your-own-cicd
  #     SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.x'
  #     - name: Deployment steps
  #       run: |
  #         cd backend
  #         npm install
  #         npm audit fix | true
  #         export NODE_OPTIONS=--openssl-legacy-provider
  #         npm install -g serverless
  #         sls deploy --verbose 

  frontend:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Installing NPM
        run: |
          cd client
          npm install
          npm audit fix | true

      - name: Building application
        run: |
          cd client
          npm run build

      - name: Generate deployment package
        run: |
          cd client
          zip -r deploy.zip * -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: TodoClient
          environment_name: TodoClient-env
          version_label: 1.0.1
          region: us-east-1
          deployment_package: client/deploy.zip
          use_existing_version_if_available: true
