name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # backend:
  #   runs-on: ubuntu-latest
  #   env:
  #   # https://www.serverless.com/framework/docs/guides/cicd/running-in-your-own-cicd
  #     SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.x'
  #     - name: Deployment steps
  #       run: |
  #         cd backend
  #         npm install
  #         npm audit fix | true
  #         export NODE_OPTIONS=--openssl-legacy-provider
  #         npm install -g serverless
  #         sls deploy --verbose 

  frontend:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Installing NPM
        run: |
          cd client
          npm install
          npm audit fix | true

      - name: Building application
        run: |
          cd client
          npm run build

      # - name: Generate deployment package
      #   run: |
      #     cd client
      #     zip -r deploy.zip * -x '*.git*'

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Install EB CLI
        run: |
          git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
          ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer

      # - name: EB Deployment
      #     run: |
      #       cd client
      #       eb deploy

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v21
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: TodoClient
      #     environment_name: TodoClient-dev
      #     version_label: 1.0.3
      #     region: us-east-1
      #     deployment_package: client/deploy.zip
      #     use_existing_version_if_available: true

      # - name: Run eb create
      #   run: |
      #   eb create TodoClient-dev --cname TodoClient-dev --elb-type application

